/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author hi
 */
public class BanHangFr extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public BanHangFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbTieude = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        pQuanlyban = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        cbbLoainuoc = new javax.swing.JComboBox<>();
        cbbTennuoc = new javax.swing.JComboBox<>();
        btnAddnuoc = new javax.swing.JButton();
        tfSoluong = new javax.swing.JTextField();
        lbSoluong = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        lbGiaVND = new javax.swing.JLabel();
        lbThanhtien = new javax.swing.JLabel();
        lbThanhtienVND = new javax.swing.JLabel();
        btnFixnuoc = new javax.swing.JButton();
        btnDeletenuoc = new javax.swing.JButton();
        btnResetnuoc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        spBangnuoc = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lbTongtien = new javax.swing.JLabel();
        lbTiennhan = new javax.swing.JLabel();
        lbTienthua = new javax.swing.JLabel();
        lbTongtienVND = new javax.swing.JLabel();
        lbTienthuaVND = new javax.swing.JLabel();
        tfTiennhan = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbBanso = new javax.swing.JLabel();
        lbBansonumber = new javax.swing.JLabel();
        lbHotennhanvien = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbNgay = new javax.swing.JLabel();
        lbDay = new javax.swing.JLabel();
        lbThoigian = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbTrong = new javax.swing.JLabel();
        lbKhachdat = new javax.swing.JLabel();
        lbDacokhach = new javax.swing.JLabel();
        lbDangchon = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");

        lbTieude.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieude.setText("Quản Lý Bán Hàng");
        lbTieude.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbTieude.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        panel1.setMinimumSize(new java.awt.Dimension(0, 0));
        panel1.setName(""); // NOI18N

        pQuanlyban.setToolTipText("");
        pQuanlyban.setName(""); // NOI18N

        javax.swing.GroupLayout pQuanlybanLayout = new javax.swing.GroupLayout(pQuanlyban);
        pQuanlyban.setLayout(pQuanlybanLayout);
        pQuanlybanLayout.setHorizontalGroup(
            pQuanlybanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        pQuanlybanLayout.setVerticalGroup(
            pQuanlybanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pQuanlyban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(pQuanlyban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cbbLoainuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại nước", "Nước ngọt", "Trà", "Trà sữa", "Nước chua" }));
        cbbLoainuoc.setToolTipText("");
        cbbLoainuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoainuocActionPerformed(evt);
            }
        });

        cbbTennuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên nước", "Nước cam", "Nước chanh", "Cà phê", "Coca", "Pepsi", "Trà đá", "Trà đá đường", "Trà sữa truyền thống", "Trà vải", " " }));

        btnAddnuoc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddnuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/add-1-icon.png"))); // NOI18N
        btnAddnuoc.setText("Thêm");
        btnAddnuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddnuoc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAddnuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddnuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnuocActionPerformed(evt);
            }
        });

        tfSoluong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoluongActionPerformed(evt);
            }
        });

        lbSoluong.setBackground(new java.awt.Color(153, 153, 255));
        lbSoluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSoluong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSoluong.setText("Số lượng");

        lbGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGia.setText("Giá:");
        lbGia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbGia.setName(""); // NOI18N

        lbGiaVND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGiaVND.setText("0 VNĐ");
        lbGiaVND.setToolTipText("");

        lbThanhtien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbThanhtien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThanhtien.setText("Thành tiền:");

        lbThanhtienVND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThanhtienVND.setText("0 VNĐ");

        btnFixnuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFixnuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/fix.png"))); // NOI18N
        btnFixnuoc.setText("Sửa");
        btnFixnuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFixnuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFixnuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixnuocActionPerformed(evt);
            }
        });

        btnDeletenuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeletenuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/delete.png"))); // NOI18N
        btnDeletenuoc.setText("Xóa");
        btnDeletenuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletenuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletenuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletenuocActionPerformed(evt);
            }
        });

        btnResetnuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetnuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/bx-reset-icon.png"))); // NOI18N
        btnResetnuoc.setText("Reset");
        btnResetnuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetnuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbTennuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoainuoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbThanhtien)
                            .addComponent(lbGia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(btnAddnuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFixnuoc)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeletenuoc)
                        .addGap(27, 27, 27)))
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbGiaVND, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbThanhtienVND, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnResetnuoc))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbLoainuoc)
                    .addComponent(lbSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGia)
                    .addComponent(lbGiaVND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTennuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoluong)
                    .addComponent(lbThanhtien)
                    .addComponent(lbThanhtienVND, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddnuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletenuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetnuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFixnuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cbbLoainuoc.getAccessibleContext().setAccessibleName("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bàn", "Tên nước", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setName(""); // NOI18N
        spBangnuoc.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spBangnuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spBangnuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbTongtien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTongtien.setText("Tổng tiền:");

        lbTiennhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTiennhan.setText("Tiền nhận:");

        lbTienthua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTienthua.setText("Tiền thừa:");

        lbTongtienVND.setText("0 VNĐ");

        lbTienthuaVND.setText("0 VNĐ");

        tfTiennhan.setToolTipText("");
        tfTiennhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTiennhanActionPerformed(evt);
            }
        });

        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Pay-Per-Click-icon.png"))); // NOI18N
        btnPay.setText("Pay");
        btnPay.setToolTipText("");
        btnPay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/printer-icon.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Home-icon.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Status-user-online-icon.png"))); // NOI18N
        lbStatus.setText("Status");
        lbStatus.setToolTipText("");
        lbStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbStatus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTienthua, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTienthuaVND)
                            .addComponent(lbTongtienVND)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbTiennhan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfTiennhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTongtien)
                            .addComponent(lbTongtienVND))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTiennhan)
                            .addComponent(tfTiennhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTienthua)
                            .addComponent(lbTienthuaVND)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                .addGap(75, 75, 75))
        );

        lbBanso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBanso.setText("Bàn số:");

        lbBansonumber.setText("0");

        lbHotennhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHotennhanvien.setText("Họ tên nhân viên:");

        lbName.setText("name");

        lbNgay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNgay.setText("Ngày:");

        lbDay.setText("day");

        lbThoigian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbThoigian.setText("Thời gian:");

        lbTime.setText("time");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTime)
                    .addComponent(lbHotennhanvien)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbBanso)
                        .addGap(18, 18, 18)
                        .addComponent(lbBansonumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbName)
                    .addComponent(lbNgay)
                    .addComponent(lbDay)
                    .addComponent(lbThoigian))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBanso)
                    .addComponent(lbBansonumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbHotennhanvien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNgay)
                .addGap(12, 12, 12)
                .addComponent(lbDay)
                .addGap(12, 12, 12)
                .addComponent(lbThoigian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTime)
                .addGap(18, 18, 18))
        );

        lbTrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Bàn trống.png"))); // NOI18N
        lbTrong.setText("Trống");
        lbTrong.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbTrong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbTrong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbKhachdat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKhachdat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Khách đặt.png"))); // NOI18N
        lbKhachdat.setText("Khách đặt");
        lbKhachdat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbKhachdat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbDacokhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDacokhach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Đã có khách.png"))); // NOI18N
        lbDacokhach.setText("Đã có khách");
        lbDacokhach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDacokhach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbDangchon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangchon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Đang được chọn.png"))); // NOI18N
        lbDangchon.setText("Đang chọn");
        lbDangchon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDangchon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lbKhachdat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDacokhach, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDangchon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTieude)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDacokhach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbKhachdat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDangchon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTrong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel1.getAccessibleContext().setAccessibleName("Đặt bàn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbLoainuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoainuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoainuocActionPerformed

    private void btnAddnuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddnuocActionPerformed

    private void tfTiennhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTiennhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTiennhanActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDeletenuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletenuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletenuocActionPerformed

    private void tfSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoluongActionPerformed

    private void btnFixnuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixnuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFixnuocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHangFr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel2;
    private javax.swing.JButton btnAddnuoc;
    private javax.swing.JButton btnDeletenuoc;
    private javax.swing.JButton btnFixnuoc;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnResetnuoc;
    private javax.swing.JComboBox<String> cbbLoainuoc;
    private javax.swing.JComboBox<String> cbbTennuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbBanso;
    private javax.swing.JLabel lbBansonumber;
    private javax.swing.JLabel lbDacokhach;
    private javax.swing.JLabel lbDangchon;
    private javax.swing.JLabel lbDay;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbGiaVND;
    private javax.swing.JLabel lbHotennhanvien;
    private javax.swing.JLabel lbKhachdat;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbThanhtien;
    private javax.swing.JLabel lbThanhtienVND;
    private javax.swing.JLabel lbThoigian;
    private javax.swing.JLabel lbTiennhan;
    private javax.swing.JLabel lbTienthua;
    private javax.swing.JLabel lbTienthuaVND;
    private javax.swing.JLabel lbTieude;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbTongtien;
    private javax.swing.JLabel lbTongtienVND;
    private javax.swing.JLabel lbTrong;
    private javax.swing.JPanel pQuanlyban;
    private javax.swing.JPanel panel1;
    private javax.swing.JScrollPane spBangnuoc;
    private javax.swing.JTextField tfSoluong;
    private javax.swing.JTextField tfTiennhan;
    // End of variables declaration//GEN-END:variables
}
